---
Name: focuspoint
---
SilverStripe\Assets\Image:
  extensions:
    - Jonom\FocusPoint\Extensions\FocusPointImage

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Jonom\FocusPoint\Extensions\LeftAndMainExtension
